# Generated by Django 3.1.7 on 2021-05-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='pizzereum',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
        ),
    ]
