# Generated by Django 3.1.7 on 2021-06-09 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders_management', '0002_orderitem_pizzereum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='pizzereum',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userFirstID', to='orders_management.order')),
                ('last_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userLastID', to='orders_management.order')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderID', to='orders_management.orderitem')),
            ],
        ),
    ]
