# Generated by Django 3.1.7 on 2021-06-09 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders_management', '0003_auto_20210609_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='pizzereum',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders_management.orderitem'),
            preserve_default=False,
        ),
    ]
