# Generated by Django 3.1.7 on 2021-06-09 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_management', '0004_leaderboard_pizzereum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='pizzereum',
        ),
    ]
