# Generated by Django 3.1.7 on 2021-06-09 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders_management', '0005_remove_leaderboard_pizzereum'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='pizzereum',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pizzereums', to='orders_management.orderitem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='first_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userFirstID', to='orders_management.order'),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='last_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userLastID', to='orders_management.order'),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orderID', to='orders_management.orderitem'),
        ),
    ]
