# Generated by Django 3.1.7 on 2021-06-09 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders_management', '0006_auto_20210609_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='first_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userFirstID', to='orders_management.order'),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='last_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userLastID', to='orders_management.order'),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderID', to='orders_management.orderitem'),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='pizzereum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pizzereums', to='orders_management.orderitem'),
        ),
    ]
