# Generated by Django 3.1.7 on 2021-06-09 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_management', '0008_auto_20210610_0243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='nickname',
        ),
    ]
