# Generated by Django 3.1.7 on 2021-06-10 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders_management', '0011_auto_20210610_0256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('nickname',)},
        ),
        migrations.AlterField(
            model_name='order',
            name='nickname',
            field=models.OneToOneField(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
