# Generated by Django 3.1.7 on 2021-06-10 00:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders_management', '0012_auto_20210610_0304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('created',)},
        ),
        migrations.RemoveField(
            model_name='order',
            name='nickname',
        ),
        migrations.AddField(
            model_name='order',
            name='nickname',
            field=models.ManyToManyField(blank=True, default=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
