# Generated by Django 3.1.7 on 2021-04-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210404_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='{slug}',
            field=models.ImageField(blank=True, upload_to='products/'),
        ),
    ]
