# Generated by Django 3.1.7 on 2021-05-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20210412_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pizzereum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
